# This config file is for the remote prisma server

managementApiSecret: PRISMA_MANAGEMENT_API_SECRET
port: 4466
databases:
  default:
    connector: postgres
    host: PRISMA_DATABASE_HOST
    port: 5432
    database: PRISMA_DATABASE_NAME
    user: PRISMA_DATABASE_USERNAME
    password: PRISMA_DATABASE_PASSWORD
    migrations: true
    ssl: true